# Generated by Django 3.1.6 on 2021-03-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konekt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_cv', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('mobility', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konekt.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=4000)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konekt.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konekt.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konekt.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konekt.experience')),
            ],
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
