# Generated by Django 3.1.6 on 2021-04-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konekt', '0003_auto_20210412_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='candidate_id',
            new_name='candidate',
        ),
    ]
