# Generated by Django 3.1.6 on 2021-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konekt', '0004_auto_20210413_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
