# Generated by Django 3.1.6 on 2021-04-28 08:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konekt', '0005_auto_20210415_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odf', 'odt'])])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='konekt.candidate')),
            ],
        ),
    ]
