# Generated by Django 3.1.6 on 2021-05-03 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konekt', '0007_auto_20210429_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='link_cv',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odf', 'odt'])]),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
